apiVersion: v1
kind: Secret
metadata:
  name: mint-replica-secrets
  labels:
    app: mint-replica
type: Opaque
data:
  database-username: <base64_encoded_username>
  database-password: <base64_encoded_password>
  redis-password: <base64_encoded_redis_password>
  jwt-secret: <base64_encoded_jwt_secret>
  plaid-client-id: <base64_encoded_plaid_client_id>
  plaid-secret: <base64_encoded_plaid_secret>
  credit-bureau-api-key: <base64_encoded_credit_bureau_api_key>
  investment-data-api-key: <base64_encoded_investment_data_api_key>

---
# Human tasks (DO NOT INCLUDE IN ACTUAL SECRETS FILE):
# - Generate and encode strong passwords for database and Redis
# - Generate a secure JWT secret for user authentication
# - Obtain and encode API keys for Plaid, credit bureau, and investment data services
# - Ensure all sensitive data is properly base64 encoded before adding to the secrets file
# - Implement a secure method for managing and rotating these secrets in production
# - Set up proper RBAC (Role-Based Access Control) to limit access to these secrets