name: Mint Replica CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push backend image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mint-replica-backend
          IMAGE_TAG: ${{ github.sha }}
        uses: docker/build-push-action@v2
        with:
          context: ./src/backend
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Build and push frontend to S3
        run: |
          npm ci
          npm run build:frontend
          aws s3 sync src/frontend/build/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster mint-replica-cluster --service mint-replica-backend-service --force-new-deployment

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

# Human tasks:
# - Set up AWS credentials and other sensitive information as GitHub secrets (Critical)
# - Configure S3 bucket for frontend deployment (Required)
# - Set up ECS cluster and service for backend deployment (Required)
# - Configure CloudFront distribution for frontend (Required)
# - Implement staging environment deployment (Optional)
# - Set up monitoring and alerting for deployment process (Optional)